version: '3.8'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_PASSWORD=userpassword
      - MARIADB_USER=user
      - MARIADB_DATABASE=film_db
    ports:
      - "3306:3306"
  spring:
    depends_on:
      - mariadb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:

      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mariadb:3306/film_db",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "rootpassword",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'